server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://${AUTH_DB_HOST:localhost}:${AUTH_DB_PORT:5432}/authdb
    username: ${AUTH_DB_USER:authuser}
    password: ${AUTH_DB_PASSWORD:authpass}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  issuer: peribook-auth-service
  expiration: PT1H  # 1 hora
  rsa:
    public-key-path: keys/jwt-public.pem
    private-key-path: keys/jwt-private.pem

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: auth-service
        url: /v3/api-docs/auth-service
      - name: user-service
        url: /v3/api-docs/user-service
      - name: post-service
        url: /v3/api-docs/post-service
      - name: like-service
        url: /v3/api-docs/like-service
      - name: bff-web
        url: /v3/api-docs/bff-web

logging:
  level:
    com.peribook: DEBUG
