services:
  post-service:
    build: .
    container_name: post-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - POST_DB_HOST=post-db
      - POST_DB_USER=postuser
      - POST_DB_PASSWORD=postpass
      - RABBITMQ_HOST=peribook-rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    depends_on:
      post-db:
        condition: service_healthy
    networks:
      - peribook-net
    restart: unless-stopped

  post-db:
    image: postgres:16-alpine
    container_name: post-db
    environment:
      POSTGRES_DB: postdb
      POSTGRES_USER: postuser
      POSTGRES_PASSWORD: postpass
    ports:
      - "5434:5432"
    volumes:
      - post-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postuser -d postdb"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - peribook-net
    restart: unless-stopped

volumes:
  post-db-data:

networks:
  peribook-net:
    name: peribook-net
    external: true
