spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"

logging:
  level:
    com.peribook: DEBUG
    org.springframework.cloud.gateway: TRACE
    org.springframework.security: DEBUG
