spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
      schema-locations: classpath:db/schema.sql

logging:
  level:
    com.peribook: DEBUG
    org.springframework.security: DEBUG
